#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap


if [ ! -f "cube_pc/cube" ]; then
   (cd cube_pc && make)
fi

if [ ! -f "firmware/main.hex" ]; then
   (cd firmware && make)
   echo "Note: Use 'make flash' to flash the firmware! Maybe need: sudo usermod -aG dailout YOURNAME, and reboot"
fi


echo "==> App is now ready to go!"